In [1]:
from IPython.core.display import HTML
def css_styling():
    styles = open("styles/custom.css", "r").read()
    return HTML(styles)
css_styling()

# Scientific Programming with NumPy

The most fundamental third-party package for scientific computing in Python is NumPy, which provides multidimensional array (`ndarray`) data structure, along with associated functions and methods to manipulate them. While Python comes with several container types (`list`,`tuple`,`dict`), NumPy's arrays are implemented closer to the hardware, and are therefore more efficient than the built-in types. 


## Basics of Numpy arrays

We now turn our attention to the NumPy library, which forms the base layer for the entire scientific Python ecosystem.  Once you have installed NumPy, you can import it as

In [2]:
import numpy

though here we will use the common shorthand

In [3]:
import numpy as np

As noted, the fundamental structure provided by NumPy is a powerful `array` object.  We'll start by exploring how the `array` differs from Python lists.  We start by creating a simple `list` and an `array` with the same contents of the list:

In [4]:
lst = list(range(1000))
arr = np.arange(1000)

# Here's what the array looks like
arr[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
type(arr)

numpy.ndarray

Elements of a one-dimensional array are indexed with square brackets, as with lists:

In [6]:
arr[5:10]

array([5, 6, 7, 8, 9])

In [7]:
arr[-1]

999

As with Python's built-in data structures, the membership of particular values can be tested with the `in` expression:

In [8]:
7 in arr

True

In [9]:
-15 in arr

False

The first difference to note between lists and arrays is that arrays are *homogeneous*; i.e. all elements of an array must be of the same type.  In contrast, lists can contain elements of mixed, arbitrary types. For example, we can change the last element in our list above to be a string:

In [10]:
lst[0] = 'a string inside a list'
lst[:10]

['a string inside a list', 1, 2, 3, 4, 5, 6, 7, 8, 9]

but the same can not be done with an array, as we get an error message:

In [11]:
arr[0] = 'a string inside an array'

ValueError: invalid literal for int() with base 10: 'a string inside an array'

The information about the type of an array is contained in its `dtype` attribute:

In [12]:
arr.dtype

dtype('int64')

Once an array has been created, its `dtype` is fixed and it can only store elements of that type.  For this example where the `dtype` is a 64-bit integer, if we store a floating point number it will be automatically converted into an integer:

In [13]:
arr[0] = 1.234
arr[:10]

array([1, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Above, we created an `array` from an existing `list`, but there is a variety of ways that we can use to create arrays. In some appliations, we may want to have an array initialized with a constant value, and very often this value is 0 or 1 (suitable as starting value for additive and multiplicative loops respectively); `zeros` creates arrays of all zeros, with any desired dtype:

In [14]:
np.zeros(5, float)

array([ 0.,  0.,  0.,  0.,  0.])

In [15]:
np.zeros(3, int)

array([0, 0, 0])

In [16]:
np.zeros(3, complex)

array([ 0.+0.j,  0.+0.j,  0.+0.j])

and similarly for `ones`:

In [17]:
print('5 ones: {0}'.format(np.ones(5)))

5 ones: [ 1.  1.  1.  1.  1.]


If we want an array initialized with an arbitrary value, we can create an empty array and then use its `fill` method to insert the value we want into the array:

In [18]:
a = np.empty(4)
a

array([  0.00000000e+000,   0.00000000e+000,   1.97626258e-323,
         0.00000000e+000])

In [19]:
a.fill(5.5)
a

array([ 5.5,  5.5,  5.5,  5.5])

### Exercise

What is another way to create an array of a particular value?

In [20]:
# Write your answer here

We have seen how the `arange` function generates an array for a range of integers. Relatedly,  the `linspace` and `logspace` functions to create linearly and logarithmically-spaced grids, respectively, with a fixed number of points, which includes both ends of the specified interval:

In [21]:
np.linspace(0, 1, num=5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [22]:
np.logspace(1, 4, num=4)

array([    10.,    100.,   1000.,  10000.])

Finally, it is often useful to create arrays with random numbers that follow a specific distribution.  The `np.random` module contains a number of functions that can be used to this effect, for example this will produce an array of 5 random samples taken from a standard normal distribution (0 mean and variance 1):

In [23]:
np.random.randn(5)

array([-1.01146186,  2.41588036,  0.25674528,  2.14052408,  1.43336972])

whereas this will also give 5 samples, but from a normal distribution with a mean of 10 and a standard deviation of 3:

In [24]:
norm10 = np.random.normal(loc=10, scale=3, size=10)

norm10

array([  6.77452001,   7.71883435,   6.63264474,   8.74226314,
        10.36046825,  11.07224689,  15.57456132,  12.10778786,
         6.81494283,  15.27264509])

### Exercise

Generate a sample of 10 values drawn from a **binomial** distribution, with `n=5` and probability `p=0.5`.

In [25]:
# Write your answer here

Computers cannot generate *true* random numbers, but rather use an algorithm to generate pseudo-random numbers that are difficult to distinguish from a true set of random numbers. NumPy employs the [Mersenne Twister algorithm](https://en.wikipedia.org/wiki/Mersenne_Twister). For a given **seed** value, the algorithm generates a deterministic sequence of numbers that can be shown to have an extremely long period.

In [26]:
np.random.seed(42)

In [27]:
np.random.random(10)

array([ 0.37454012,  0.95071431,  0.73199394,  0.59865848,  0.15601864,
        0.15599452,  0.05808361,  0.86617615,  0.60111501,  0.70807258])

To illustrate that this is a deterministic algorithm, we can re-seed the pseudo-random number generator and draw values again:

In [28]:
np.random.seed(42)

In [29]:
np.random.random(10)

array([ 0.37454012,  0.95071431,  0.73199394,  0.59865848,  0.15601864,
        0.15599452,  0.05808361,  0.86617615,  0.60111501,  0.70807258])

## Indexing with other arrays

Above we saw how to index arrays with single numbers and slices, just like Python lists.  But arrays allow for a more sophisticated ("fancy") kind of indexing which is very powerful: you can index an array with another array:

In [30]:
arr[[5, 10, 15]]

array([ 5, 10, 15])

This is particluarly useful to extract information from an array that matches a certain condition, using a **boolean** values.

Imagine that in the array `norm10` we want to replace all values larger than 9 with the value 0.  We can do this by first creating a *mask* that indicates where this condition is true or false:

In [31]:
mask = norm10 > 9
mask

array([False, False, False, False,  True,  True,  True,  True, False,  True], dtype=bool)

Notice that the mask is just an array of `bool` elements; we can use it to either index those values or to reset them to 0:

In [32]:
norm10[mask]

array([ 10.36046825,  11.07224689,  15.57456132,  12.10778786,  15.27264509])

In [33]:
norm10[mask] = 0

norm10

array([ 6.77452001,  7.71883435,  6.63264474,  8.74226314,  0.        ,
        0.        ,  0.        ,  0.        ,  6.81494283,  0.        ])

### Exercise

Create a 4 x 4 matrix of ones, then change the first two columns of the first two rows to zeros.

In [34]:
# Write your answer here

## Multidimensional Arrays

The NumPy type `ndarray` stands for *n-dimensional array*. Hence, arrays can be constructed of aribtrary dimension. For example, a list of lists can be used to initialize a two dimensional array:

In [35]:
lst2 = [[1, 2], [3, 4]]
arr2 = np.array([[1, 2], [3, 4]])
arr2.shape

(2, 2)

With two-dimensional arrays we start seeing the power of NumPy arrays: while a nested list can be indexed by chaining the `[ ]` operator, `ndarray` supports a much more natural indexing syntax with a single `[ ]` and a set of indices separated by commas:

In [36]:
lst2[0][1]


2

In [37]:
arr2[0,1]

2

Most of the array creation functions listed above can be used with more than one dimension, for example:

In [38]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [39]:
np.random.normal(10, 3, size=(2, 4))

array([[  8.59157684,  11.62768013,   8.60974692,   8.60281074],
       [ 10.72588681,   4.26015927,   4.8252465 ,   8.31313741]])

Using the `reshape` method, the shape of an array can be changed at any time, as long as the total number of elements is unchanged.  

For example, if we want a 2x4 array with numbers increasing from 0:

In [40]:
arr = np.arange(8).reshape(2,4)

arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

Or a 4x2 array:

In [41]:
arr.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

Notice that the `reshape` function creates a new array and does not itself modify the original array (*i.e.* it is not an *in-place* operation).

In [42]:
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

This array can be reverted to its original one-dimensional shape with the `flatten1` method or function:

In [43]:
arr.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

With multidimensional arrays, you can also index with slices, and you can mix and match slices and single indices among the axes of an array:

In [44]:
arr[1, 2:4]

array([6, 7])

In [45]:
arr[:, 2]

array([2, 6])

If you only provide one index, then you will index the first dimension (*i.e.* row):

In [46]:
arr[1]

array([4, 5, 6, 7])

Now that we have seen how to create arrays with more than one dimension, let's look at some of the most useful attributes and methods that arrays have. 

The following provide basic information about the size, shape and data in the array:

In [47]:
print('Data type                :', arr.dtype)
print('Total number of elements :', arr.size)
print('Number of dimensions     :', arr.ndim)
print('Shape (dimensionality)   :', arr.shape)
print('Memory used (in bytes)   :', arr.nbytes)

Data type                : int64
Total number of elements : 8
Number of dimensions     : 2
Shape (dimensionality)   : (2, 4)
Memory used (in bytes)   : 64


Arrays also have many useful summarization methods, incuding:

In [48]:
print('Minimum and maximum             :', arr.min(), arr.max())
print('Sum and product of all elements :', arr.sum(), arr.prod())
print('Mean and standard deviation     :', arr.mean(), arr.std())

Minimum and maximum             : 0 7
Sum and product of all elements : 28 0
Mean and standard deviation     : 3.5 2.29128784748


The above operations are computed over *all* the elements of the array.  But for a multidimensional array, it is possible to restrict the computation to a single dimension, by passing the `axis` parameter:

In [49]:
arr.sum(axis=0)

array([ 4,  6,  8, 10])

In [50]:
arr.sum(axis=1)

array([ 6, 22])

As you can see in this example, the value of the `axis` parameter is the dimension which will be *consumed* once the operation has been carried out.  Thus, `axis=0` sums across rows.  

### Exercise

Create an array with 4 dimensions and shape `(3,4,5,6)`. Then, sum along the axis number 2 (i.e. the *third* axis).  Check the shape of the resulting array.

In [72]:
# Write your answer here

Another widely used property of arrays with multiple dimensions is the `.T` attribute, which accesses the transpose of the array:

In [52]:
arr.T

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

Notice that `T` is an attribute, and not a method call. Equivalently,

In [53]:
arr.transpose()

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [54]:
np.transpose(arr)

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

There is a wide variety of methods and properties of arrays.       

In [55]:
[attr for attr in dir(arr) if not attr.startswith('__')]

['T',
 'all',
 'any',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'astype',
 'base',
 'byteswap',
 'choose',
 'clip',
 'compress',
 'conj',
 'conjugate',
 'copy',
 'ctypes',
 'cumprod',
 'cumsum',
 'data',
 'diagonal',
 'dot',
 'dtype',
 'dump',
 'dumps',
 'fill',
 'flags',
 'flat',
 'flatten',
 'getfield',
 'imag',
 'item',
 'itemset',
 'itemsize',
 'max',
 'mean',
 'min',
 'nbytes',
 'ndim',
 'newbyteorder',
 'nonzero',
 'partition',
 'prod',
 'ptp',
 'put',
 'ravel',
 'real',
 'repeat',
 'reshape',
 'resize',
 'round',
 'searchsorted',
 'setfield',
 'setflags',
 'shape',
 'size',
 'sort',
 'squeeze',
 'std',
 'strides',
 'sum',
 'swapaxes',
 'take',
 'tobytes',
 'tofile',
 'tolist',
 'tostring',
 'trace',
 'transpose',
 'var',
 'view']

## Sorting

There are several ways of sorting the values of an array. If we take a random array of integers (via the `randint` function), we can sort it using the `sort` function:

In [56]:
random_integers = np.random.randint(10, size=10)
random_integers

array([9, 2, 6, 3, 8, 2, 4, 2, 6, 4])

In [57]:
np.sort(random_integers)

array([2, 2, 2, 3, 4, 4, 6, 6, 8, 9])

The `sort` method will perform the sort *in place*:

In [58]:
random_integers.sort()

Or, we can use the `sorted` function from the Python standard library, but it will return a `list` rather than an array:

In [59]:
sorted(random_integers)

[2, 2, 2, 3, 4, 4, 6, 6, 8, 9]

Notice that the random integer array contains duplicates of certain values. The `unique` function returns an array of just the unique values:

In [60]:
np.unique(random_integers)

array([2, 3, 4, 6, 8, 9])

Its also possible to sort array values **indirectly** using `argsort`. This returns the array of index values that would sort the array if used as an index. For example, take 5 individual weights:

In [61]:
height = np.array([71, 71, 63, 74, 65])

This yields the sequence of index values:

In [62]:
np.argsort(height)

array([2, 4, 0, 1, 3])

To verify this, try using them to index `height`.

In [63]:
# Write your answer here

Notice that for the tied values, the sorting algorlithm simply kept them in their original order.

It is possible to sort multiple arrays of variables as a group, as you would sort columns in a spreadsheet. Suppose, for example, we had a second array of values corresponding to the weights of the individuals for which we already have the heights. We can use the `lexsort` function to sort them lexically, with the last array being used as the primary sort index.

`lexsort` expects a tuple or array of sequences.

In [64]:
weight = np.array([201, 186, 164, 198, 170])

In [65]:
sort_index = np.lexsort((weight, height))

We can confirm that these sort the values correctly:

In [66]:
height[sort_index]

array([63, 65, 71, 71, 74])

Notice that the tied weight values were sorted according to weight:

In [67]:
weight[sort_index]

array([164, 170, 186, 201, 198])

## Array Operations

Arrays support all regular arithmetic operators, and the NumPy library also includes a rich collection of basic and advanced mathematical functions that operate on arrays.  It is important to remember that, in general, all operations with arrays are applied *element-wise*, i.e., are applied to all the elements of the array at the same time.  Consider for example:

In [68]:
arr1 = np.arange(4)
arr2 = np.arange(10, 14)
arr_sum = arr1 + arr2

print('{0} + {1} = {2}'.format(arr1, arr2, arr_sum))

[0 1 2 3] + [10 11 12 13] = [10 12 14 16]


Importantly, the multiplication operator is also applied element-wise, it is *not* the matrix multiplication from linear algebra (as is the case in Matlab, for example):

In [69]:
print('{0} X {1} = {2}'.format(arr1, arr2, arr1*arr2))

[0 1 2 3] X [10 11 12 13] = [ 0 11 24 39]


While this means that arrays to which arithmetic operators are applied must have matching dimensions, NumPy will *broadcast* dimensions when possible.  For example, suppose that you want to add the number 1.5 to `arr1`; the following would be a valid way to do it:

In [70]:
arr1 + 1.5*np.ones(4)

array([ 1.5,  2.5,  3.5,  4.5])

But thanks to NumPy's broadcasting rules, the following is equally valid:

In [71]:
arr1 + 1.5

array([ 1.5,  2.5,  3.5,  4.5])

In this case, NumPy looked at both operands and saw that the first (`arr1`) was a one-dimensional array of length 4 and the second was a scalar (considered a zero-dimensional object), and expanded the second to match the dimension of the first. 

The broadcasting rules allow numpy to:

* *create* new dimensions of length 1 (since this doesn't change the size of the array)
* 'stretch' a dimension of length 1 that needs to be matched to a dimension of a different size.

So in the above example, the scalar 1.5 is effectively:

* first 'promoted' to a 1-dimensional array of length 1
* then, this array is 'stretched' to length 4 to match the dimension of `arr1`.

After these two operations are complete, the addition can proceed as now both operands are one-dimensional arrays of length 4.

This broadcasting behavior is powerful, especially because it doesn't require that  the data be replicated in order to match the larger dimensions.  In the example above the operation is carried *as if* the 1.5 was a 1-d array with 1.5 in all of its entries, but no array is created in memory.  This is important for cases when the arrays in question are large and replication can have significant performance implications.

The general rule is: when operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions, and works its way forward, creating dimensions of length 1 as needed. Two dimensions are considered compatible when

* they are equal to begin with, or
* one of them is 1; in this case numpy will do the 'stretching' to make them equal.

If these conditions are not met, a `ValueError: frames are not aligned` exception is thrown, indicating that the arrays have incompatible shapes. The size of the resulting array is the maximum size along each dimension of the input arrays.

This shows how the broadcasting rules work in several dimensions:

In [73]:
b = np.array([2, 3, 4, 5])
bcast_sum = arr + b

print('{0}\n\n+ {1}\n{2}\n{3}'.format(arr, b, '-'*12, bcast_sum))

[[0 1 2 3]
 [4 5 6 7]]

+ [2 3 4 5]
------------
[[ 2  4  6  8]
 [ 6  8 10 12]]


Now, how could you use broadcasting to say add `[4, 6]` along the rows to `arr` above?  Simply performing the direct addition will produce the error we previously mentioned:

In [74]:
c = np.array([4, 6])
arr + c

ValueError: operands could not be broadcast together with shapes (2,4) (2,) 

According to the rules above, the array `c` would need to have a *trailing* dimension of 1 for the broadcasting to work.  NumPy allows you to 'inject' new dimensions anywhere into an array on the fly, by indexing it with `None` (or the special object `np.newaxis`):

In [75]:
c

array([4, 6])

In [76]:
cplus = c[:, None, None]
cplus

array([[[4]],

       [[6]]])

This is exactly what we need, and indeed it works:

In [77]:
arr + cplus

array([[[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[ 6,  7,  8,  9],
        [10, 11, 12, 13]]])

For the full broadcasting rules, please see the official Numpy docs, which describe them in detail and with more complex examples.

### Exercises

Generate the following structure as a numpy array, without typing the values by hand. Then, create another array containing just the 2nd and 4th rows.

        [[1,  6, 11],
         [2,  7, 12],
         [3,  8, 13],
         [4,  9, 14],
         [5, 10, 15]]

In [78]:
# Write your answer here

Generate a 10 x 3 array of random numbers (in range [0,1]). For each row, pick the number closest to 0.5.

*Hints*:

* NumPy functions/methods that may be useful here include `abs`, `choose` and `argsort` 


## Linear Algebra

Numpy ships with a basic linear algebra library, and all arrays have a `dot` method whose behavior is that of the scalar dot product when its arguments are vectors (one-dimensional arrays) and the traditional matrix multiplication when one or both of its arguments are two-dimensional arrays:

In [79]:
v1 = np.array([2, 3, 4])
v2 = np.array([1, 0, 1])
dprod = v1.dot(v2)

print(v1, '.', v2, '=', dprod)

[2 3 4] . [1 0 1] = 6


There is an equivalent `dot` function:

In [80]:
np.dot(v1, v2)

6

Here is a regular matrix-vector multiplication, note that the array `v1` should be viewed as a **column** vector in traditional linear algebra notation; NumPy makes no distinction between row and column vectors and simply verifies that the dimensions match the required rules of matrix multiplication, in this case we have a $2 \times 3$ matrix multiplied by a 3-vector, which produces a 2-vector:

In [81]:
A = np.arange(6).reshape(2, 3)

In [82]:
print(A.shape, v1.shape)

(2, 3) (3,)


In [83]:
A.dot(v1)

array([11, 38])

For matrix-matrix multiplication, the same dimension-matching rules must be satisfied, e.g. consider the difference between $A \times A^T$:

In [84]:
A.dot(A.T)

array([[ 5, 14],
       [14, 50]])

and $A^T \times A$:

In [85]:
A.T.dot(A)

array([[ 9, 12, 15],
       [12, 17, 22],
       [15, 22, 29]])

Furthermore, the `numpy.linalg` module includes additional functionality such as determinants, matrix norms, Cholesky, eigenvalue and singular value decompositions, etc.  For even more linear algebra tools, `scipy.linalg` contains the majority of the tools in the classic LAPACK libraries as well as functions to operate on sparse matrices.  We refer the reader to the [NumPy](http://docs.scipy.org/doc/numpy/reference/) and [SciPy](http://docs.scipy.org/doc/scipy/reference/) documentation for additional details on these.

## Reading and writing arrays to disk

Numpy lets you read and write arrays into files in a number of ways.  In order to use these tools well, it is critical to understand the difference between a *text* and a *binary* file containing numerical data.  In a text file, the number $\pi$ could be written as "3.141592653589793", for example: a string of digits that a human can read, with in this case 15 decimal digits.  

In contrast, that same number written to a binary file would be encoded as 8 characters (bytes) that are not readable by a human but which contain the exact same data that the variable `pi` had in the computer's memory.  

The tradeoffs between the two modes are thus:

* **Text mode**: occupies more space, precision can be lost (if not all digits are written to disk), but is readable and editable by hand with a text editor.  Can *only* be used for one- and two-dimensional arrays.

* **Binary mode**: compact and exact representation of the data in memory, can't be read or edited by hand.  Arrays of any size and dimensionality can be saved and read without loss of information.

First, let's see how to read and write arrays in text mode.  The `np.savetxt` function saves an array to a text file, with options to control the precision, separators and even adding a header:

In [86]:
arr = np.arange(10).reshape(2, 5)
np.savetxt('test.out', arr, fmt='%.2e', header="My dataset")

In [87]:
!cat test.out

# My dataset
0.00e+00 1.00e+00 2.00e+00 3.00e+00 4.00e+00
5.00e+00 6.00e+00 7.00e+00 8.00e+00 9.00e+00


And this same type of file can then be read with the matching `np.loadtxt` function:

In [88]:
arr2 = np.loadtxt('test.out')
arr2

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.]])

For binary data, Numpy provides the `np.save` and `np.savez` routines.  `np.save` saves a single array to a file with `.npy` extension, while `np.savez` can be used to save a **group** of arrays into a single file with `.npz` extension.  The files created with these routines can then be read with the `np.load` function.

Let us first see how to use the simpler `np.save` function to save a single array:

In [89]:
np.save('test.npy', arr2)

Now we can read this back.

In [90]:
arr2n = np.load('test.npy')

Let's see if any element is non-zero in the difference. A value of True would be a problem.

In [91]:
np.any(arr2 - arr2n)

False

Now let us see how the `np.savez` function works.  You give it a filename and either a sequence of arrays or a set of keywords.  In the first mode, the function will auotmatically name the saved arrays in the archive as `arr_0`, `arr_1`, etc:

In [92]:
np.savez('test.npz', arr, arr2)
arrays = np.load('test.npz')
arrays.files

['arr_1', 'arr_0']

Alternatively, we can explicitly name the arrays we save using keyword arguments for `savez`:

In [93]:
np.savez('test.npz', array1=arr, array2=arr2)
arrays = np.load('test.npz')
arrays.files

['array1', 'array2']

The object returned by `np.load` from an `.npz` file works like a dictionary:

In [94]:
# First row of array
arrays['array1'][0]

array([0, 1, 2, 3, 4])

Equivalently, you can access its constituent files by attribute using its special `.f` field:

In [95]:
arrays.f.array1[0]

array([0, 1, 2, 3, 4])

This `.npz` format is a very convenient way to package compactly and without loss of information, into a single file, a group of related arrays that pertain to a specific problem.  At some point, however, the complexity of your dataset may be such that the optimal approach is to use one of the standard formats in scientific data processing that have been designed to handle complex datasets, such as NetCDF or HDF5.  

### Exercise

Generate a 10 x 3 array of random numbers (in range [0,1]). For each row, pick the number closest to 0.5.

*Hints*:

* NumPy functions/methods that may be useful here include `abs` and `argsort` 


In [96]:
# Write your answer here

## References

[Scientific Python Lecture Notes](http://scipy-lectures.github.io)